#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

# 1. 載入環境變數
if [ -f .env ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    # 忽略註解與空行
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue

    if [[ "$line" == *"="* ]]; then
      key="${line%%=*}"
      value="${line#*=}"
      # 去除首尾引號與空白
      key=$(echo "$key" | xargs)
      value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
      export "$key"="$value"
    fi
  done <.env
fi

CONTAINER_NAME="${CONTAINER_NAME:-db2-gtky}"
INSTANCE_USER="db2inst1"
BACKUP_ROOT_IN_CONTAINER="/database/backups"

# 2. 自動偵測容器工具 (podman 或 docker)
CONTAINER_TOOL=""
if command -v podman >/dev/null 2>&1 && podman ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  CONTAINER_TOOL="podman"
elif command -v docker >/dev/null 2>&1 && docker ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  CONTAINER_TOOL="docker"
else
  if command -v podman >/dev/null 2>&1; then
    CONTAINER_TOOL="podman"
  elif command -v docker >/dev/null 2>&1; then
    CONTAINER_TOOL="docker"
  else
    echo "錯誤: 系統未安裝 podman 或 docker。"
    exit 1
  fi
fi

# 3. 檢查容器是否運行
if ! $CONTAINER_TOOL ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  echo "錯誤: 容器 '$CONTAINER_NAME' 並未運行。"
  echo "請先使用以下指令啟動容器："
  echo "   $CONTAINER_TOOL-compose up -d"
  exit 1
fi

echo "使用容器工具: $CONTAINER_TOOL"
echo "正在連接 DB2 取得資料庫清單..."

# 4. 取得資料庫清單
DB_LIST_RAW=$($CONTAINER_TOOL exec -i "$CONTAINER_NAME" su - "$INSTANCE_USER" -c "db2 list db directory" 2>/dev/null || true)
DB_LIST=$(echo "$DB_LIST_RAW" | awk -F'=' '/Database alias/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' | grep -v '^$' | sort -u)

if [ -z "$DB_LIST" ]; then
  echo "錯誤: 無法從 DB2 取得資料庫清單。請確認實例已啟動。"
  exit 1
fi

# 5. 決定備份目標
TARGET_DBS=""
if [ $# -gt 0 ]; then
  INPUT_DB="$1"
  if echo "$DB_LIST" | grep -qix "$INPUT_DB"; then
    TARGET_DBS=$(echo "$DB_LIST" | grep -ix "$INPUT_DB")
  else
    echo "錯誤: 資料庫 '$INPUT_DB' 不存在於 DB2 中。"
    echo "目前可用的資料庫清單："
    echo "$DB_LIST" | sed 's/^/ - /'
    exit 1
  fi
else
  echo "=========================================="
  echo "請選擇要備份的資料庫："
  echo "=========================================="

  IFS=$'\n' read -rd '' -a dbs <<<"$DB_LIST" || true

  select opt in "${dbs[@]}" "=== 備份所有資料庫 ===" "=== 取消 ==="; do
    case "$opt" in
    "=== 取消 ===")
      echo "已取消備份。"
      exit 0
      ;;
    "=== 備份所有資料庫 ===")
      TARGET_DBS="$DB_LIST"
      break
      ;;
    *)
      if [ -n "$opt" ]; then
        TARGET_DBS="$opt"
        break
      else
        echo "選項無效，請輸入正確的數字。"
      fi
      ;;
    esac
  done
fi

# 6. 執行備份流程
for db in $TARGET_DBS; do
  echo "----------------------------------------------------"
  echo "正在處理資料庫: $db"

  # 備份目錄在容器內建立，宿主機透過 bind mount 直接看到 ./backups/$db
  $CONTAINER_TOOL exec -i "$CONTAINER_NAME" bash -c \
    "mkdir -p '$BACKUP_ROOT_IN_CONTAINER/$db' && chown $INSTANCE_USER '$BACKUP_ROOT_IN_CONTAINER/$db'"

  # DB2 目前是循環日誌 (circular logging)，只支援離線備份，
  # 所以要先斷開所有連線並停用資料庫。
  echo "執行 DB2 離線備份指令..."
  BACKUP_OUTPUT=$($CONTAINER_TOOL exec -i "$CONTAINER_NAME" su - "$INSTANCE_USER" -c "
      db2 connect reset >/dev/null 2>&1 || true
      db2 force applications all >/dev/null 2>&1 || true
      sleep 3
      db2 deactivate database $db >/dev/null 2>&1 || true
      db2 backup database $db to $BACKUP_ROOT_IN_CONTAINER/$db compress
  ")
  echo "$BACKUP_OUTPUT"

  # DB2 的備份檔名由自己決定，時間戳是還原時 TAKEN AT 要用的關鍵資訊
  TIMESTAMP=$(echo "$BACKUP_OUTPUT" | grep -oE '[0-9]{14}' | tail -1)
  if [ -z "$TIMESTAMP" ]; then
    echo "錯誤: 備份失敗，無法取得備份時間戳。"
    exit 1
  fi

  # 產生 metadata.json
  echo "產生/更新 metadata.json..."
  $CONTAINER_TOOL exec -i "$CONTAINER_NAME" bash -c "cat > '$BACKUP_ROOT_IN_CONTAINER/$db/metadata.json'" <<EOF
{
  "database": "$db",
  "db2Version": "12.1",
  "source": "backup.sh",
  "timestamp": "$TIMESTAMP",
  "createdAt": "$(date +%Y-%m-%d)",
  "description": "Backup of $db database generated by backup.sh"
}
EOF

  echo "資料庫 '$db' 備份成功！"
  echo "備份檔位置: ./backups/$db/ (timestamp $TIMESTAMP)"
done

echo "=========================================="
echo " 所有備份程序已完成。"
echo "=========================================="
